### ISSUE TITLE
Sophisticated styling props

### ISSUE THREAD

**Issue by tobimori** [coralic/kirby-extended-writer#6]

**Comment by jonasfeige** [comment]
Hi @tobimori , this feature sounds really good, but how does it actually work? Couldn't find anything in the docs.

**Comment by tobimori** [comment]
@jonasfeige 
https://github.com/coralic/kirby-extended-writer/blob/main/src/plugins/writerTextAlign.js

For now, this plugin adds an `align` property to the Writer field to align the text in the panel only. I already planned to remove this functionality in the next release, and encourage you to rather create a custom plugin or custom panel css for styling panel fields. 

I don't use it anymore, because it feels confusing to me if text in inputs is centered or right-aligned. Furthermore, I wanted to pick this plugin up again for a while, but I'm packed with projects where I can't use Kirby 😦 so my time lacks for this.

**Comment by jonasfeige** [comment]
> 

Thanks for the quick response! Makes perfect sense. Good luck with those projects!
